name: Sphinx
on:
  pull_request:

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"
      - name: Build Documentation
        run: |
          pip install -e .[docs]
          make html
      - name: Push Documentation
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "Github Actions Bot"
          git add -f build/html
          git commit -m "Build Documentation"
          git subtree push --force --prefix build/html origin gh-pages
