name: Sphinx
on:
  pull_request:

jobs:
  sphinx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          architecture: "x64"
          cache: "pip"
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: build/html
      - name: Build Documentation
        run: |
          pip install -e .[docs]
          make html
      - name: Push Documentation
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "Github Actions Bot"
          touch build/html/.nojekyll # keep _* folders
          cd build/html
          git add .
          git commit -m "Build Documentation"
          git push origin gh-pages || true
